services:
  imgproxy:
    container_name: chult-imgproxy
    image: ghcr.io/imgproxy/imgproxy:latest
    command: imgproxy -keypath /run/secrets/IMGPROXY_KEY -saltpath /run/secrets/IMGPROXY_SALT
    environment:
      # Basic config
      IMGPROXY_BIND: '0.0.0.0:8080'
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /var/lib/imgproxy
      IMGPROXY_USE_ETAG: 'true'
      IMGPROXY_TTL: 3600

      # Security - generate these with: openssl rand -hex 64
      # IMGPROXY_KEY: '' # Now passed in as file
      # IMGPROXY_SALT: '' # Now passed in as file
      IMGPROXY_SIGNATURE_SIZE: 32

      # Format settings
      IMGPROXY_AUTO_WEBP: 'true'
      IMGPROXY_ENFORCE_WEBP: 'true'
      IMGPROXY_AUTO_AVIF: 'true'
      IMGPROXY_AVIF_SPEED: 8 # Faster AVIF encoding

      # TIMEOUT SETTINGS - key for large images
      IMGPROXY_TIMEOUT: 60
      IMGPROXY_READ_REQUEST_TIMEOUT: 60
      IMGPROXY_DOWNLOAD_TIMEOUT: 60
      IMGPROXY_KEEP_ALIVE_TIMEOUT: 10

      # Processing optimization
      IMGPROXY_STRIP_METADATA: 'true' # Remove metadata for smaller files
      IMGPROXY_STRIP_COLOR_PROFILE: 'true' # Remove color profile
      IMGPROXY_RETURN_ATTACHMENT: 'false' # Faster delivery

      # Limits for large D&D maps
      IMGPROXY_MAX_SRC_FILE_SIZE: '${PUBLIC_MAX_IMAGE_SIZE}' # 50MB
      IMGPROXY_MAX_SRC_DIMENSION: 16000 # 16000px (was 8000px)
      IMGPROXY_MAX_SRC_RESOLUTION: 268435456 # 268MP (16384x16384)
      IMGPROXY_MAX_ANIMATION_FRAMES: 1 # Static maps only

      # Performance
      IMGPROXY_WORKERS: 1
      IMGPROXY_MAX_CLIENTS: 50
      IMGPROXY_PRESETS: 'thumbnail=resize:fit:300:300:0:0/quality:70,small=resize:fit:800:800:0:0/quality:80,medium=resize:fit:1280:1280:0:0/quality:85,large=resize:fit:1920:1920:0:0/quality:90'

      # Caching
      IMGPROXY_CACHE_CONTROL_PASSTHROUGH: 'true'
      IMGPROXY_SET_CANONICAL_HEADER: 'true'
    volumes:
      - ${UPLOADS_PATH}:/var/lib/imgproxy:ro # Read-only access to uploads
      - imgproxy_cache:/tmp/imgproxy # Named volume for better performance
    secrets:
      - IMGPROXY_KEY
      - IMGPROXY_SALT
    ports:
      - '8080:8080'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'imgproxy', 'health']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  postgres:
    container_name: chult-postgres
    image: postgres:18-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    command: >
      postgres -c shared_buffers=512MB -c effective_cache_size=1536MB -c maintenance_work_mem=128MB -c work_mem=8MB -c max_connections=15 -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c default_statistics_target=150 -c random_page_cost=1.0 -c effective_io_concurrency=200 -c min_wal_size=512MB -c max_wal_size=2GB -c max_parallel_workers_per_gather=2 -c max_parallel_workers=4 -c max_parallel_maintenance_workers=2 -c parallel_tuple_cost=0.05 -c parallel_setup_cost=500 -c wal_compression=zstd -c wal_init_zero=off -c wal_recycle=on -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=10 -c tcp_keepalives_count=3 -c log_min_duration_statement=1000 -c log_line_prefix='%t [%p]: user=%u,db=%d '


    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
        reservations:
          cpus: '0.5'
          memory: 1G
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  adminer:
    container_name: chult-adminer
    image: adminer:latest
    ports:
      - '8081:8080' # Adminer default port is 8080, map to 8081 on host
    environment:
      ADMINER_DEFAULT_SERVER: postgres # Connect to the 'postgres' service
    depends_on:
      - postgres # Ensure postgres starts before adminer
    restart: unless-stopped

secrets:
  IMGPROXY_KEY:
    environment: IMGPROXY_KEY
  IMGPROXY_SALT:
    environment: IMGPROXY_SALT
  POSTGRES_USER:
    environment: POSTGRES_USER
  POSTGRES_PASSWORD:
    environment: POSTGRES_PASSWORD
  POSTGRES_DB:
    environment: POSTGRES_DB

volumes:
  postgres_data: {}
  imgproxy_cache: {}
